### PR TITLE
update css & logos

### PR DESCRIPTION
**Pull request by mbutterick**
Minimal changes needed to make navbar on `pkgs` match the main Racket site.

### CODE REVIEW

**Comment by samth** [comment]
A similar PR to https://github.com/tonyg/racket-pkg-website/ might also be a good idea (that's the source of pkgn.racket-lang.org and the future replacement for pkgs.racket-lang.org).

**Comment by mbutterick** [comment]
[Give a dude a chance! ](https://github.com/tonyg/racket-pkg-website/pull/32)

**Comment by mbutterick** [comment]
@jeapostrophe do you mind if I merge this PR?

**Comment by jeapostrophe** [comment]
Sorry for the delay. I just did it and pushed it to the server

**Comment by mbutterick** [comment]
FWIW, after 30+ days, I see the same design at http://pkgs.racket-lang.org/

Is this another cache-related issue? (see [related issue](https://github.com/racket/racket-lang-org/issues/44) with the main website)

**Comment by samth** [comment]
@jeapostrophe can you check what the server is serving?

**Comment by jeapostrophe** [comment]
Alright, it is fixed.

**Pull request merged**
